<a href="https://colab.research.google.com/github/sab112/myfirstrepo/blob/master/mycrossValuation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
# cross valuation is used take diff folds of data and fit diff models with diff parameters, to check and get the best model out of all
# cross valuation splits the data into folds e.g 3 folds
# feature = [1,2,3,4,5,6,7,8,9]
# target = [1,2,3,4,5,6,7,8,9]
#                       train       test                        train         test
# folds of feature = [3 4 5 6 7 8] [0 1 2]  folds of target = [3 4 5 6 7 8] [0 1 2]
#                    [0 1 2 6 7 8] [3 4 5]                    [0 1 2 6 7 8] [3 4 5]
#                    [0 1 2 3 4 5] [6 7 8]                    [0 1 2 3 4 5] [6 7 8]

# cross valuation 'fit' the model for all three train data of by one and calculate the 'score' with test data                   
                 
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

from sklearn.datasets import load_digits

In [35]:
digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [36]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)   #cv=3 is no.of folds

array([0.89482471, 0.95325543, 0.90984975])

In [37]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [38]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.93155259, 0.94323873, 0.91819699])

In [39]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
scores1

array([0.83888889, 0.89444444, 0.87777778, 0.80555556, 0.89444444,
       0.9       , 0.87777778, 0.91620112, 0.88268156, 0.87709497])

In [40]:
np.average(scores1)

0.8764866542520174

In [41]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9410086902545002

In [42]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9448975791433891

In [43]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.946570453134699