<a href="https://colab.research.google.com/github/sab112/myfirstrepo/blob/master/myLinearReg_houseAreaPrice_multipleVariable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [56]:
a=[[2600,3,20,550000],
[3000,4,15,565000],
[3200,np.nan,18,610000],
[3600,3,30,595000],
[4000,5,8,760000]]
df = pd.DataFrame(a,columns=('area','bedrooms','age','price'))
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [57]:
#clean or pre-process the data #take median and fill the NaN
mb = df['bedrooms'].median()
median_bedrooms = int(mb)
median_bedrooms 

3

In [58]:
df['bedrooms'] = df['bedrooms'].fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [62]:
feature = df[['area','bedrooms','age']]
target = df['price']
print(feature)
print(target)


   area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       3.0   18
3  3600       3.0   30
4  4000       5.0    8
0    550000
1    565000
2    610000
3    595000
4    760000
Name: price, dtype: int64


In [63]:
reg = linear_model.LinearRegression()
reg.fit(feature,target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [66]:
reg.coef_   #m for area, bedrooms,age    y = m1*area +m1*bedrooms +m1*age + b

array([   137.25, -26025.  ,  -6825.  ])

In [67]:
reg.intercept_    #b - y_intercept

383724.99999999994

In [76]:
#3000 sqft 3 bd 40 age
reg.predict([[3000,3,40]])

array([444400.])

In [77]:
#how it works
y = 137.25 * 3000 + -26025 * 3 + -6825 * 40 + 383724.99999999994
y

444399.99999999994

In [78]:
reg.predict([[2500,4,5]])

array([588625.])