<a href="https://colab.research.google.com/github/sab112/myfirstrepo/blob/master/myStockPrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [200]:
import quandl
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

In [201]:
quandl.ApiConfig.api_key='8sea8tfXW2CSAPzEYUoq'
df= quandl.get('XNSE/BAJAJ_AUTO')
df 

Open         High  ...  Adjustment Factor  Adjustment Type
Date                                  ...                                    
2010-01-01   669.844609   669.844609  ...                NaN              NaN
2010-01-04   673.738166   676.772851  ...                NaN              NaN
2010-01-05   667.554280   670.741654  ...                NaN              NaN
2010-01-06   668.012346   668.012346  ...                NaN              NaN
2010-01-07   657.705870   659.996198  ...                NaN              NaN
...                 ...          ...  ...                ...              ...
2018-12-25  2550.461719  2550.461719  ...                NaN              NaN
2018-12-26  2540.211758  2574.003867  ...                NaN              NaN
2018-12-27  2587.202446  2587.296053  ...                NaN              NaN
2018-12-28  2577.841751  2583.504972  ...                NaN              NaN
2018-12-31  2562.958247  2586.359984  ...                NaN              NaN

[2347 rows x 7 columns]

In [202]:
cdf = df[['Close']] 
cdf 

Close
Date                   
2010-01-01   669.844609
2010-01-04   661.160448
2010-01-05   664.214219
2010-01-06   653.945915
2010-01-07   642.475188
...                 ...
2018-12-25  2550.461719
2018-12-26  2559.775610
2018-12-27  2562.022177
2018-12-28  2543.768822
2018-12-31  2546.249406

[2347 rows x 1 columns]

In [203]:
forecast_out = 30
cdf['prediction_col'] = cdf[['Close']].shift(-forecast_out) #new column is added with data from close column, but no first 30 in Close column(list of lists)
cdf

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


Close  prediction_col
Date                                   
2010-01-01   669.844609      682.804048
2010-01-04   661.160448      684.292761
2010-01-05   664.214219      686.144110
2010-01-06   653.945915      702.042804
2010-01-07   642.475188      691.869930
...                 ...             ...
2018-12-25  2550.461719             NaN
2018-12-26  2559.775610             NaN
2018-12-27  2562.022177             NaN
2018-12-28  2543.768822             NaN
2018-12-31  2546.249406             NaN

[2347 rows x 2 columns]

In [204]:
x = np.array(cdf.drop(['prediction_col'],1))  #Close column alone, prediction_column is dropped
x = x[:-forecast_out]                         #removing last 30 rows
print(cdf)
print(x)

                  Close  prediction_col
Date                                   
2010-01-01   669.844609      682.804048
2010-01-04   661.160448      684.292761
2010-01-05   664.214219      686.144110
2010-01-06   653.945915      702.042804
2010-01-07   642.475188      691.869930
...                 ...             ...
2018-12-25  2550.461719             NaN
2018-12-26  2559.775610             NaN
2018-12-27  2562.022177             NaN
2018-12-28  2543.768822             NaN
2018-12-31  2546.249406             NaN

[2347 rows x 2 columns]
[[ 669.844609]
 [ 661.160448]
 [ 664.214219]
 ...
 [2498.229042]
 [2523.034883]
 [2508.338592]]


In [205]:
y = np.array(cdf['prediction_col'])   #prediction_column column alone, but this 1D, if you want 2D like x, give 1 more [] - cdf[['prediction_col']]
y = y[:-forecast_out]                 #removing last 30 rows
y                                     # x - feature, y - label/target. x is 2D(list of lists(but here 1D is represented in 2D)), y is 1D(list)
                                      #so that 1 close column is mapped with every prediction_col in ML algo to create a model

array([ 682.804048,  684.292761,  686.14411 , ..., 2562.022177,
       2543.768822, 2546.249406])

In [206]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)   #split the data, 80% for training, 20% for testing 

In [207]:
svr_rbf = SVR(kernel='rbf',C=1e3,gamma=0.1)        #construct/instanciate SVR algo class
svr_rbf.fit(x_train,y_train)                       #fit/create a model with feature,lable/target

SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.1,
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [208]:
lr = LinearRegression()                      #construct/instanciate LinearRegression algo class
lr.fit(x_train,y_train)                      #fit/create a model with feature,lable/target

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [209]:
predict_score_svr = svr_rbf.score(x_test,y_test)   #get accurancy of predition of model created with trainf data, 
                                                   #by calling score(20%test_feature, 20%test_lable)
print(predict_score_svr)
predict_score_lr = lr.score(x_test,y_test)
print(predict_score_lr)

0.8898923347709302
0.950540909292394


In [210]:
x_forecast = np.array(cdf.drop(['prediction_col'],1))  #prediction_column column alone, but this 1D, if you want 2D like x, give 1 more [] - cdf[['prediction_col']]
x_forecast = x_forecast[-forecast_out:]                #this time take only last 30
print(x_forecast.shape)
print(x_forecast)

(30, 1)
[[2496.029279]
 [2438.133381]
 [2424.747587]
 [2424.747587]
 [2480.116097]
 [2433.453034]
 [2437.431329]
 [2549.853274]
 [2570.165982]
 [2561.086108]
 [2587.155643]
 [2587.38966 ]
 [2544.330464]
 [2608.076796]
 [2550.88295 ]
 [2564.455958]
 [2666.300318]
 [2654.786663]
 [2642.664563]
 [2659.3266  ]
 [2659.279797]
 [2679.966932]
 [2702.619814]
 [2628.904342]
 [2550.461719]
 [2550.461719]
 [2559.77561 ]
 [2562.022177]
 [2543.768822]
 [2546.249406]]


In [211]:
svr_rbf_predict = svr_rbf.predict(x_forecast)   #svr model's predict..last 30 Close column's prediction_col(label) by passing feature alone
print(svr_rbf_predict)
lr_predict = lr.predict(x_forecast)            #lr model's predict..last 30 Close column's prediction_col(label) by passing feature alone
print(lr_predict)

[2613.09007255 2520.39700612 2412.58534978 2412.58534978 2568.49672676
 2571.95888577 2483.49866321 2594.73490603 2608.88657209 2520.4599931
 2549.9229074  2552.21549101 2559.07107903 2622.97688372 2560.32269208
 2571.56341272 2423.19866734 2473.07180417 2507.78012695 2632.99262789
 2630.9146945  2552.44594085 2572.85420514 2575.18278062 2573.09030681
 2573.09030681 2544.22188944 2508.76164407 2538.76782652 2560.10698226]
[2495.74536022 2440.05657235 2427.18107221 2427.18107221 2480.43882128
 2435.55464976 2439.38128401 2547.51747436 2567.05582035 2558.32208974
 2583.3978007  2583.6228965  2542.20520518 2603.52139653 2548.507897
 2561.56347416 2659.5253187  2648.45058779 2636.79060706 2652.8174531
 2652.77243433 2672.6709334  2694.46024117 2623.55495385 2548.10272419
 2548.10272419 2557.0615506  2559.22247387 2541.66497412 2544.05099318]
