<a href="https://colab.research.google.com/github/sab112/myfirstrepo/blob/master/myStockPrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [237]:
#take a column as 'feature', use same column as 'label' to create a model and predict next in the sequence 
import quandl
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

In [238]:
quandl.ApiConfig.api_key='8sea8tfXW2CSAPzEYUoq'
df= quandl.get('XNSE/BAJAJ_AUTO')
df 

Open         High  ...  Adjustment Factor  Adjustment Type
Date                                  ...                                    
2010-01-01   669.844609   669.844609  ...                NaN              NaN
2010-01-04   673.738166   676.772851  ...                NaN              NaN
2010-01-05   667.554280   670.741654  ...                NaN              NaN
2010-01-06   668.012346   668.012346  ...                NaN              NaN
2010-01-07   657.705870   659.996198  ...                NaN              NaN
...                 ...          ...  ...                ...              ...
2018-12-25  2550.461719  2550.461719  ...                NaN              NaN
2018-12-26  2540.211758  2574.003867  ...                NaN              NaN
2018-12-27  2587.202446  2587.296053  ...                NaN              NaN
2018-12-28  2577.841751  2583.504972  ...                NaN              NaN
2018-12-31  2562.958247  2586.359984  ...                NaN              NaN

[2347 rows x 7 columns]

In [239]:
cdf = df[['Close']] 
cdf 

Close
Date                   
2010-01-01   669.844609
2010-01-04   661.160448
2010-01-05   664.214219
2010-01-06   653.945915
2010-01-07   642.475188
...                 ...
2018-12-25  2550.461719
2018-12-26  2559.775610
2018-12-27  2562.022177
2018-12-28  2543.768822
2018-12-31  2546.249406

[2347 rows x 1 columns]

In [240]:
forecast_out = 30
cdf['prediction_col'] = cdf[['Close']].shift(-forecast_out) #new column is added with data from close column, but no first 30 in Close column(list of lists)
cdf

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


Close  prediction_col
Date                                   
2010-01-01   669.844609      682.804048
2010-01-04   661.160448      684.292761
2010-01-05   664.214219      686.144110
2010-01-06   653.945915      702.042804
2010-01-07   642.475188      691.869930
...                 ...             ...
2018-12-25  2550.461719             NaN
2018-12-26  2559.775610             NaN
2018-12-27  2562.022177             NaN
2018-12-28  2543.768822             NaN
2018-12-31  2546.249406             NaN

[2347 rows x 2 columns]

In [241]:
x = np.array(cdf.drop(['prediction_col'],1))  #Close column alone, prediction_column is dropped
x = x[:-forecast_out]                         #removing last 30 rows
print(cdf)
print(x)

                  Close  prediction_col
Date                                   
2010-01-01   669.844609      682.804048
2010-01-04   661.160448      684.292761
2010-01-05   664.214219      686.144110
2010-01-06   653.945915      702.042804
2010-01-07   642.475188      691.869930
...                 ...             ...
2018-12-25  2550.461719             NaN
2018-12-26  2559.775610             NaN
2018-12-27  2562.022177             NaN
2018-12-28  2543.768822             NaN
2018-12-31  2546.249406             NaN

[2347 rows x 2 columns]
[[ 669.844609]
 [ 661.160448]
 [ 664.214219]
 ...
 [2498.229042]
 [2523.034883]
 [2508.338592]]


In [242]:
y = np.array(cdf['prediction_col'])   #prediction_column column alone, but this 1D, if you want 2D like x, give 1 more [] - cdf[['prediction_col']]
y = y[:-forecast_out]                 #removing last 30 rows
y                                     # x - feature, y - label/target. x is 2D(list of lists(but here 1D is represented in 2D)), y is 1D(list)
                                      #so that 1 close column is mapped with every prediction_col in ML algo to create a model

array([ 682.804048,  684.292761,  686.14411 , ..., 2562.022177,
       2543.768822, 2546.249406])

In [243]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)   #split the data, 80% for training, 20% for testing 

In [244]:
svr_rbf = SVR(kernel='rbf',C=1e3,gamma=0.1)        #construct/instanciate SVR algo class
svr_rbf.fit(x_train,y_train)                       #fit/create a model with feature,lable/target

SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.1,
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [245]:
lr = LinearRegression()                      #construct/instanciate LinearRegression algo class
lr.fit(x_train,y_train)                      #fit/create a model with feature,lable/target

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [246]:
predict_score_svr = svr_rbf.score(x_test,y_test)   #get accurancy of predition of model created with trainf data, 
                                                   #by calling score(20%test_feature, 20%test_lable)
print(predict_score_svr)
predict_score_lr = lr.score(x_test,y_test)
print(predict_score_lr)

0.9019214049967401
0.9431565028048865


In [247]:
x_forecast = np.array(cdf.drop(['prediction_col'],1))  #prediction_column column alone, but this 1D, if you want 2D like x, give 1 more [] - cdf[['prediction_col']]
x_forecast = x_forecast[-forecast_out:]                #this time take only last 30
print(x_forecast.shape)
print(x_forecast)

(30, 1)
[[2496.029279]
 [2438.133381]
 [2424.747587]
 [2424.747587]
 [2480.116097]
 [2433.453034]
 [2437.431329]
 [2549.853274]
 [2570.165982]
 [2561.086108]
 [2587.155643]
 [2587.38966 ]
 [2544.330464]
 [2608.076796]
 [2550.88295 ]
 [2564.455958]
 [2666.300318]
 [2654.786663]
 [2642.664563]
 [2659.3266  ]
 [2659.279797]
 [2679.966932]
 [2702.619814]
 [2628.904342]
 [2550.461719]
 [2550.461719]
 [2559.77561 ]
 [2562.022177]
 [2543.768822]
 [2546.249406]]


In [248]:
svr_rbf_predict = svr_rbf.predict(x_forecast)   #svr model's predict..last 30 Close column's prediction_col(label) by passing feature alone
print('svr - ',svr_rbf_predict)
lr_predict = lr.predict(x_forecast)            #lr model's predict..last 30 Close column's prediction_col(label) by passing feature alone
print('lr - ',lr_predict)                              #i.e. next 30 days forecast/prediction

svr -  [2591.87576865 2416.14355162 2437.49532475 2437.49532475 2538.20621767
 2662.01391079 2363.44196923 2615.28919822 2515.59898941 2553.62309579
 2438.5588248  2471.43466578 2588.07085951 2588.19368455 2580.12812434
 2698.00536414 2415.38355465 2481.18433522 2619.68393255 2621.83983629
 2620.20595684 2561.06271939 2542.97822632 2600.74246768 2595.73710059
 2595.73710059 2573.8056152  2588.530284   2551.15590099 2589.26419328]
lr -  [2491.84089578 2436.31202098 2423.47349348 2423.47349348 2476.57831032
 2431.82302588 2435.63867177 2543.46434378 2562.94658446 2554.23793317
 2579.24163801 2579.46608743 2538.16732904 2599.30744795 2544.45192237
 2557.4700098  2655.15055213 2644.10762285 2632.48112432 2648.4619485
 2648.417059   2668.25841856 2689.98515727 2619.28347793 2544.04791303
 2544.04791303 2552.98101374 2555.13573181 2537.62864928 2540.00781677]
